version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - easytest-network
    ports:
      - "5432:5432"
    env_file:
      - .docker.env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: adminer
    networks:
      - easytest-network
    ports:
      - "15432:80"
    env_file:
      - .docker.env
networks:
  easytest-network:
    driver: bridge