version: '3.3'

services:
  app:
    container_name: easytest-backend
    image: easytest-backend
    networks:
      - easytest-network
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
networks:
  easytest-network:
    driver: bridge